<div style="text-align: center"> <h1>Exercises 12</h1></div>
<div style="text-align: center; color: red;"> <h2>Numpy</h2></div>

<div style="color: white;text-align:center;background-color:darkblue;padding:5px;"> <h2>Exercise 01</h2></div>

<div style="color:darkblue;"> <h3>Create an 3d numpy array with dimensions (4, 5, 3), and print the dimensions finally.</h3></div>

In [2]:
import numpy as np

In [3]:
arr = np.array([
                [
                    [1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 12, 34],
                    [3, 4, 7]
                ],
                [
                    [1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 12, 34],
                    [3, 4, 7]
                ],
                [
                     [1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 12, 34],
                    [3, 4, 7]
                ],
                [
                     [1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 12, 34],
                    [3, 4, 7]
                ]
               ])

In [4]:
print(f"Shape of the array : {arr.shape}.")

print(f"Dimensions of the array : {arr.ndim}.")

Shape of the array : (4, 5, 3).
Dimensions of the array : 3.


<div style="color: white;text-align:center;background-color:darkblue;padding:5px;"> <h2>Exercise 02</h2></div>

<div style="color:darkblue;"> <h3>change the shape of created array in the exercise 01 to (20, 3) and check the current dimensions! </h3></div>

In [6]:
new_arr = arr.reshape(20,3)
print(new_arr)

print(f"Shape: {new_arr.shape}.")
print(new_arr.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 12 34]
 [ 3  4  7]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 12 34]
 [ 3  4  7]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 12 34]
 [ 3  4  7]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 12 34]
 [ 3  4  7]]
Shape: (20, 3).
2


<div style="color: white;text-align:center;background-color:darkblue;padding:5px;"> <h2>Exercise 03</h2></div>

<div style="color:darkblue;"> <h3>index and print the number 50 from the arr.</h3></div>

### arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

In [7]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
arr[1,0]

50

<div style="color: white;text-align:center;background-color:darkblue;padding:5px;"> <h2>Exercise 04</h2></div>

<div style="color:darkblue;"> <h3>Change the element datatype of the arr to float!</h3></div>

### arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

In [19]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
arr.astype(float)

array([[10., 20., 30., 40.],
       [50., 60., 70., 80.]])

In [24]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
np.float64(arr)

array([[10., 20., 30., 40.],
       [50., 60., 70., 80.]])

In [33]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]], dtype = "d")
arr
arr.dtype

dtype('float64')

<div style="color: white;text-align:center;background-color:darkblue;padding:5px;"> <h2>Exercise 05</h2></div>

<div style="color:darkblue;"> <h3>join arr1 and arr2 into a single array!</h3></div>

### arr1 = np.array([1, 2, 3])
### arr2 = np.array([4, 5, 6])

In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [15]:
arr3 = np.concatenate((arr1, arr2))
print(f'Joined {arr1} and {arr2} by "concatenate" :\n {arr3}\n')

arr4 = np.vstack((arr1,arr2)) 
print(f'Joined {arr1} and {arr2} by "vstack" :\n {arr4}\n')

arr5 = np.hstack((arr1,arr2)) 
print(f'Joined {arr1} and {arr2} by "hstack" :\n {arr5}')


Joined [1 2 3] and [4 5 6] by "concatenate" :
 [1 2 3 4 5 6]

Joined [1 2 3] and [4 5 6] by "vstack" :
 [[1 2 3]
 [4 5 6]]

Joined [1 2 3] and [4 5 6] by "hstack" :
 [1 2 3 4 5 6]
